service: llm-trial

provider:
  name: aws
  region: ap-southeast-2
  stage: dev
  timeout: 900
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
  environment:
    AZURE_OPENAI_API_KEY:
    AZURE_OPENAI_ENDPOINT:
    PROXY_CURL:
  ecr:
    images:
      llm-trial:
        path: ./

functions:
  api:
    image:
      name: llm-trial
    timeout: 900
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    noDeploy:
      - pip
      - autopep8
      - debugpy

package:
  exclude:
    - node_modules/**
    - .dockerignore
    - Dockerfile
    - docker-compose*
